### ISSUE TITLE
[1.12.2] Locks up after using Pocket multiple times

### ISSUE THREAD

**Issue by festro** [TheRealZeher/DimensionalPockets-II#100]
Activating the pocket dimension multiple time will cause the game to freeze (entering and exiting)
MC 1.12.2
5.2.101-beta-clientonly.jar
7.2.05-universal.jar
Can't give a crash report as the game doesn't generate one for the issue I'm having
[latest.log](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/10108804/latest.log)
I'm playing singleplayer so I'm not sure whether that counts as server or client.

**Comment by TheCosmicNebula** [comment]
Looks like a missing mapping. I do apologise, but the 1.12.2 version is EOL (End of life) as newer versions are being maintained. This is not a critical bugfix, so this will not be fixed.

**Comment by festro** [comment]
Ok, I just rolled back to the previous version and it's working fine.
