### ISSUE TITLE
[1.19.2] Stuck on "loading terrain" entering pocket dimension

### ISSUE THREAD

**Issue by robbenrose** [TheRealZeher/DimensionalPockets-II#101]
Mod version 8.2.1.90
Cosmos-library version 8.2.2.0
Singleplayer world

[latest.log](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/10717513/latest.log)
[debug.log](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/10717514/debug.log)

**Comment by robbenrose** [comment]
When I close and relaunch the client I end up in a purple dimension consisting solely of a layer of water on top of a layer of bedrock. I can only get back to the overworld with commands.
The same dimension appears when Dimensional Pockets 2 is the only mod enabled, but I don't get stuck on the loading terrain page.

**Comment by TheCosmicNebula** [comment]
This is most likely an issue with the version of Forge you are using. I will look into it and update the mod to the latest stable version.

**Comment by TheCosmicNebula** [comment]
In reference to the bedrock and water, that is by design as in previous versions if you had certain mods installed, you could end up being teleported high in the sky and falling into the void.

**Comment by TheCosmicNebula** [comment]
There is nothing in either log that points to an issue. I don't even see when you placed the Dimensional Pocket block so I will have to test this issue myself.

**Comment by TheCosmicNebula** [comment]
This should have been fixed with the latest release for 1.19.2. Since you have not responded in a month, I am going to assume this issue is fixed.
