### ISSUE TITLE
[1.19.2] Ore Generation not functioning

### ISSUE THREAD

**Issue by TorinnTheDragon** [TheRealZeher/DimensionalPockets-II#103]
Minecraft Version: 1.19.2
Mod Version: 1.19.2-8.3.0.26
Cosmos Library Version: 1.19.2-8.2.2.0
Crash Report: there isn't any
Running the client side (single player)

So I have made a new instance of a single player world and I tried to look for the Dimensional Ore and couldn't find a single ore out there and use insane methods in Creative to clear out the world and found no ore spawned in and saw that there wasn't a ore config in the config file.

So my request would be like maybe a way to edit Ore spawning in the config file.

Thanks

**Comment by TorinnTheDragon** [comment]
Please I would love to see if someone can view this issue

**Comment by TheCosmicNebula** [comment]
Apologies for the delay, I will look into the issue.

**Comment by TorinnTheDragon** [comment]
> Apologies for the delay, I will look into the issue.

Hope that everything is alright so far and also I hope you took the suggestion in consideration as well

**Comment by TheCosmicNebula** [comment]
Hi, I have not yet had a chance to look into this issue, as my job has kept me busy. I aim to investigate this Saturday. I may consider adding config for ore spawning, and I have had many comments about its appearance. I need to tweak it, but am not sure the config will happen. I'll keep you updated. Apologies for the delay
