### ISSUE TITLE
[1.19.2] Setspawn command always setting spawnpoint to 15, 2, 15 no matter where I stand.

### ISSUE THREAD

**Issue by freariose** [TheRealZeher/DimensionalPockets-II#104]
The /dim setspawn command is always setting the spawn point to 15, 2, 15 no matter where I stand or what gamemode I am in. I've tried a variety of spots in both creative and survival. I'm in a singleplayer world, and this is the only pocket dimension. I tried to see if there was anything else I could do with the /dim setspawn command, but the wiki doesn't mention anything and nothing worked in game.

**Comment by TheCosmicNebula** [comment]
Hi, thank you for the report. I will look into this issue within the next few weeks after I return from a family holiday.

**Comment by TheCosmicNebula** [comment]
This has now been fixed as of version 1.19.2-8.3.1.10. Apologies for the delay.
