### ISSUE TITLE
my server crashed due to a issie with the mod for version 1.12.2

### ISSUE THREAD

**Issue by Thunderrock424242** [TheRealZeher/DimensionalPockets-II#105]
[latest (6).log](https://github.com/CosmosMods/DimensionalPocketsII/files/11888859/latest.6.log)

**Comment by Thunderrock424242** [comment]
Or could you tell me what's making it incompatible with something?

**Comment by TheCosmicNebula** [comment]
Hi, it's an error with Commands, did you run any from the server?

**Comment by TheCosmicNebula** [comment]
Apologies for the late reply also.
