### ISSUE TITLE
[1.19.2] Stuck on loading terrain screen when leaving Pocket before waiting

### ISSUE THREAD

**Issue by Pootleris** [TheRealZeher/DimensionalPockets-II#107]
forge 1.19.2 43.2.21. when i enter the pocket it loads as usual, however if i don't wait 1-2 mins before leaving i get in an infinite loading terrain screen, while being able to hear sounds and being hit. the only wait to fix it in game is by being teleported to another dimension or being kicked. dim pocket version 8.3.0.26 / cosmos version 8.2.2.0. minecraft run on server and joined from client. i tried multiple forge versions but nothing seems to change.

**Comment by Pootleris** [comment]
[client_mods.txt](https://github.com/CosmosMods/DimensionalPocketsII/files/12291544/client_mods.txt)
[server_mods.txt](https://github.com/CosmosMods/DimensionalPocketsII/files/12291545/server_mods.txt)

here's a list of the mods on both server and client.

**Comment by TheCosmicNebula** [comment]
Can you provide a log file for when this happens? Server and client if possible.

**Comment by Pootleris** [comment]
[server log.txt](https://github.com/CosmosMods/DimensionalPocketsII/files/12315289/server.log.txt)
[client log.txt](https://github.com/CosmosMods/DimensionalPocketsII/files/12315290/client.log.txt)

here you go. I see a lot of errors in the client log?

**Comment by Pootleris** [comment]
EDIT: Found the culprit: https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge.

(in fact: https://github.com/iPortalTeam/ImmersivePortalsModForForge/issues/66)

Immersive Portals doesn't work properly when switching dimensions too fast, meaning this wasn't a Dimensional Pockets II problem; also happens with other dimensions. Im sorry for the trouble!

**Comment by TheCosmicNebula** [comment]
Not a problem, glad you found the issue!
