### ISSUE TITLE
Opening Gui of a Pocket and Entering a Pocket and problems with moving after some time

### ISSUE THREAD

**Issue by Craft94land** [TheRealZeher/DimensionalPockets-II#110]
i have problems opening the pockets gui and it doesnt matter what kind of pocket it is once i placed it down and right clicked it it says i cant interact with the settings of the pocket and when i try to wrench the block to get it back in my inventory it says only the owner of a pocket can pick it up but im the owner of the pocket and when i let pass some time i cant move or push any button except esc. im really confused i would like to try the mod but cant because of these problems.

**Comment by TheCosmicNebula** [comment]
Hi, you need to shift right click first to set yourself as an owner.

**Comment by Craft94land** [comment]
hi cass and thx for the quick response do you mean while placing

________________________________
Von: Cass ***@***.***>
Gesendet: Dienstag, 9. Januar 2024 10:26
An: CosmosMods/DimensionalPocketsII ***@***.***>
Cc: Craft94land ***@***.***>; Author ***@***.***>
Betreff: Re: [CosmosMods/DimensionalPocketsII] Opening Gui of a Pocket and Entering a Pocket and problems with moving after some time (Issue #110)


Hi, you need to shift right click first to set yourself as an owner.

**Comment by TheCosmicNebula** [comment]
No, once you have placed it down, you need to enter the Pocket by shift right clicking.

**Comment by Craft94land** [comment]
i tried that but it says that im not the owner of the pocket
________________________________
Von: Cass ***@***.***>
Gesendet: Dienstag, 9. Januar 2024 10:29
An: CosmosMods/DimensionalPocketsII ***@***.***>
Cc: Craft94land ***@***.***>; Author ***@***.***>
Betreff: Re: [CosmosMods/DimensionalPocketsII] Opening Gui of a Pocket and Entering a Pocket and problems with moving after some time (Issue #110)


No, once you have placed it down, you need to enter the Pocket by shift right clicking.

**Comment by TheCosmicNebula** [comment]
Hmm. What version of the mod and minecraft are you using?

**Comment by Craft94land** [comment]
im playing in 1.19.2 forge 43.2.6 in the KSYNC 2 Enter the Wild modpack the mod is in the version 1.19.2-8.3.0.26 universal.jar
________________________________
Von: Cass ***@***.***>
Gesendet: Dienstag, 9. Januar 2024 10:31
An: CosmosMods/DimensionalPocketsII ***@***.***>
Cc: Craft94land ***@***.***>; Author ***@***.***>
Betreff: Re: [CosmosMods/DimensionalPocketsII] Opening Gui of a Pocket and Entering a Pocket and problems with moving after some time (Issue #110)


Hmm. What version of the mod and minecraft are you using?

**Comment by TheCosmicNebula** [comment]
Have you re-bound your sneak key?

**Comment by Craft94land** [comment]
i have to shift place it be an owner of a pocket i tried it and i worked
________________________________
Von: Cass ***@***.***>
Gesendet: Dienstag, 9. Januar 2024 10:34
An: CosmosMods/DimensionalPocketsII ***@***.***>
Cc: Craft94land ***@***.***>; Author ***@***.***>
Betreff: Re: [CosmosMods/DimensionalPocketsII] Opening Gui of a Pocket and Entering a Pocket and problems with moving after some time (Issue #110)


Have you re-bound your sneak key?

**Comment by TheCosmicNebula** [comment]
Great 👍
