### ISSUE TITLE
Outside dimensional pockets

### ISSUE THREAD

**Issue by HighTemplar0** [TheRealZeher/DimensionalPockets-II#111]
This isn't exactly an issue, more of a question, but is there a way to make the outside of the dimensional pockets completeley void? if players manage to glitch in/out of pockets they can find their way to other ones which might be problematic. Sorry if this doesn't belong here but i had no idea how to ask this question other than github

**Comment by TheCosmicNebula** [comment]
Hi,

Thanks for the feedback. The world inside the pockets is designed to protect players in the event they do end up outside their Pocket. It is the way it's designed that all Pockets are in 1 world to be efficient with space. There are many protections in place to stop users getting outside but it is inevitable they will.

If you could provide explanations of how they are getting out I can add those methods to the blocking list in the next public version.

**Comment by HighTemplar0** [comment]
Sorry for the late response

Ice and fire dragons allows you to summon dragons inside the pocket dimension, this is good as you can then use those dragons for dragon forges, however if the dragon is big enough and you ride it, you can simply pop out of your box.

This allows you to move freely towards other boxes, however i later noticed that i cannot summon other dragons while outside the box, but i can place blocks as normal.

This just scares me as people could possibly glitch back in (like the way people glitch on top of the nether with ender pearls) and raid/grief the dimension. by being able to place blocks you can also place down waypoints or teleporters from waystones and mekanism, which would allow you to freely move out of a dimension.

I know im asking a lot, but its also nice to keep the ability to teleport into a box without the box using waystones and teleporters.

the mod similar to this, compact machines, has void outside the boxes, so if you glitch out you will fall and die. I think that making it impossible to place blocks outside of the cubes will work to prevent anything.

Feel free to ask me any questions you may have.
