### ISSUE TITLE
[1.20.1] Dimensional Tome [WIP] only shows last page

### ISSUE THREAD

**Issue by MummyXYZ** [TheRealZeher/DimensionalPockets-II#112]
Minecraft Version: 1.20.1
Mod version: 9.0.0.0
Cosmos-Library Version.: 10.1.0.0
Full crash report: Not a crash issue but here is latest.log https://gist.github.com/MummyXYZ/030b14c32b5be6cd7d463549133a5c96

This is being run on single player but has the same result when opening to LAN.

When opening the Tome it seems to default to the page 47 and will not change. I can see other information briefly when clicking on different tabs but it immediately reverts back to page 47.

Short video showing the issue: https://youtu.be/AvjL90R0zYk

**Comment by TheCosmicNebula** [comment]
This issue was fixed as of version 1.20.1-9.0.3.10
