### ISSUE TITLE
[1.20.1] Server crash: Exception ticking world crash when entering Pocket Dimension.

### ISSUE THREAD

**Issue by Gbergz** [TheRealZeher/DimensionalPockets-II#114]
# Server Crash with Forge 47.3.1

### Info:
Basically entering a Pocket Dimension causes an Exception ticking world crash. Not sure how to exactly reproduce it, but somewhere in that area.

Something related to a compound tag?

```
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "com.tcn.dimensionalpocketsii.pocket.core.gson.PocketChunkInfo.save(net.minecraft.nbt.CompoundTag)" because "this.chunk_info" is null
```
Full crash-report here: https://gist.githubusercontent.com/Gbergz/f4219f8cb6e0130ef0538aceee2c6215/raw/62c2d05f0a08df818a0230cf39e9f7ee98a730ec/gistfile1.txt

Edit: latest.log here: (related error & crash at the bottom.)
https://gist.githubusercontent.com/Gbergz/87bf73444acd1b3644824c076d3afbce/raw/3eada8d078802a616e2a75bf8b206d8075b0bd43/gistfile1.txt

Edit 2:
This issue started to happen after updating Forge from 47.2.17 to 47.3.1 so maybe something changed in Forge that needs to be looked into, not sure.

### Versions:
MC: 1.20.1
Forge: 47.3.1
Dimensional Pockets: 9.0.9.0

**Comment by TheCosmicNebula** [comment]
Hi, apologies for the late reply. I will have to take a look into this issue with Forge 47.3.1.

**Comment by TheCosmicNebula** [comment]
Crash was not easily apparent when moving to Forge 47.3.1. This will be investigated in the 1.21 NeoForge version.
