### ISSUE TITLE
[1.20.1] UUID Changed: Loss Of Access To DP

### ISSUE THREAD

**Issue by LightInShadows** [TheRealZeher/DimensionalPockets-II#115]
Minecraft Version. 1.20.1
    Mod version. TNW ++ 3 0.7.zip
    Cosmos-Library Version. 1.20.1-10.5.1.0
    No Crash Report as there was no crash
    Whether you where running it on a server, or a client: Server

Apparently the players UUID changed over night and they lost all access to everything including the character reset.

**Comment by TheCosmicNebula** [comment]
Hi, there is a way to update this, I have responded to your message on the Discord

**Comment by TheCosmicNebula** [comment]
Manual tweak provided to pocketRegistry.dat on July 13th 2024.
