### ISSUE TITLE
[1.20.1] [Feature Request] Allow other mods to charge items wirelessly/from inventory

### ISSUE THREAD

**Issue by Chifilly** [TheRealZeher/DimensionalPockets-II#116]
- Minecraft Version: `1.20.1`
- Forge Version: `47.3.1`
- Mod version: `9.0.8.0`
- Cosmos-Library Version: `10.5.1.0`
- Playing using the `TNP: Limitless 7` modpack

It would be nice if other mods could charge the tools and armour of this mod. I've currently tried; Powah's Energy Cells, Batteries and Player Transmitters; Flux Networks' wireless charging; Thermal Series' Flux Capacitors; and Mekanism's Charge Pad, but none of it works. I've also tried the item-based batteries in the curio slots, in inventory and on the hotbar and they don't work either.

When I'm going on a big manual mining expedition, the Elytraplate runs out of power so quickly (even with the Armour Module Battery, which sadly can't be stacked), and if I don't notice then I can't quickly hop into the pocket dimension to charge it since it's out of juice, so I have to go all the way home to charge it or find a little bit of sunlight to get enough charge to shift into it (which can be hard to come by and tedious since if the Elytraplate is out of power, then so is my pickaxe). But every other item in every other mod can be charged wirelessly using any of the mods I've tried (or semi-wirelessly with Batteries/Flux Capacitors and having that wirelessly charged).

Unless I'm missing something somehow to enable this, or some note somewhere as to why it's not a thing, or I'm a massive idiot and it is a thing but I need an upgrade I haven't noticed or something, I think it would be a good idea to implement it, because it's become quite tedious completely running out of power and I'm tempted to ditch it for another solution until I can get the Mekanism MekSuit.

_I will say though, the pocket dimension itself is great, and the 31x31 one is refreshing to see considering most other mods of this type limit you to a chunk or less_

**Comment by TheCosmicNebula** [comment]
Thanks for the feedback. I have looked into allowing my items to charge wirelessly before and I remember it being a bear. What I can do, and have been thinking of doing recently, is to adjust the power drain rates of the tools and the Elytraplate itself. This will allow it to last longer. You can also use a Dimensional Energy Cell or Enhanced version which should give you at least double the run time. To use, charge and place onto your hotbar, shift right click it and it will begin charging everything in your inventory. It should have the enchantment glint when it is working.

**Comment by Chifilly** [comment]
Interesting. I would have thought it would be simple because so many mods do it. I assumed it would be as simple as hooking into the Forge Energy API or something (I'm not a mod developer so I wouldn't know, just going by semi-educated guesses of a fellow programmer). But thanks for the info!

I was thinking about using the Energy Cell, but the fact it has to be on the hotbar turned me off. I only have 4 free slots in my hotbar because there are 5 things I want to have there 24/7 already, and the fact it doesn't work in-inventory or is able to use a curio slot put me off (hence why I mentioned Powah and Thermal's batteries, since they work in-inventory and in curio slots). Lowering power drain would be useful though, or even the ability to stack the Armour Module Battery would be great, and/or be able to put the upgrade in the other armour pieces so they can contribute to the power spread and storage too.

**Comment by TheCosmicNebula** [comment]
Seems simple, but in reality, for me at least it is anything but. I can look into it again, but no guarantees.

I will certainly attend to the power rates, and adding more battery modules to the Elytraplate and other Enhanced armour is a decent idea as well, so keep an eye out.

**Comment by TheCosmicNebula** [comment]
This will be looked at in the 1.21 NeoForge port. For now I believe I adjusted the rates of all energy consuming Items / Armour. For now, I recommend making a few Enhanced Energy Cells and using them, as they can charge items inside your inventory when activated you the hotbar.
