### ISSUE TITLE
[1.20.1] Can't join the world if I've logged out in my pocket before. OutOfMemoryError

### ISSUE THREAD

**Issue by DrSigma4164** [TheRealZeher/DimensionalPockets-II#117]
I'm playing on a dedicated server, if I'm in my pocket and exit the server and try to re-enter the server, I can't do it. It just loads for a long time and then shows an error about OutOfMemory, or an error that a packet was received that was larger than 20000 bytes when it was expected to be 0 bytes.

Versions:
minecraft: 1.20.1
forge: 47.3.1
dimensionalpocket: 9.1.0.0

Logs:
latest: https://gist.github.com/DrSigma4164/2f84b9970eb6fedb319a4080e42a9eb8
debug: https://gist.github.com/DrSigma4164/0eb858ec4fe62a5251d71dceb1e37901

**Comment by TheCosmicNebula** [comment]
Hi, thanks for the report.

I can't see anything in there that would suggest it's my mod causing the issue, the AutoModPack mod seems to be loading many config files.

How many mods are you running? Are you able to test the server with less mods?

**Comment by DrSigma4164** [comment]
I will try to test with less mods, however I am playing a modpack with close to 550 mods. Automodpack simply downloads mods from the server to the client. I've dropped a profile below with the mods I'm using.
[MineMods_1_20_1.zip](https://github.com/user-attachments/files/17535354/MineMods_1_20_1.zip)

**Comment by DrSigma4164** [comment]
So, I've tested all my mods in singleplayer and I can't reproduce this bug in singleplayer.
However, as I wrote earlier, the problem is with the game on a dedicated server, but I can't check it now. Could you try to play it on a dedicated server because the thing is that I don't know how to run the server, my friend is running the server and he can't test it yet, maybe later I can do it, but could you try to do it. Thank you.

**Comment by DrSigma4164** [comment]
However, while I was testing, I crashed once when entering a pocket, and this time I got a crash log. There are a few mods out there that could be the cause. Here is this log file:
[crash-2024-10-28_18.43.58-client.txt](https://github.com/user-attachments/files/17548012/crash-2024-10-28_18.43.58-client.txt)
[latest.log](https://github.com/user-attachments/files/17548013/latest.log)
[debug.log](https://github.com/user-attachments/files/17548014/debug.log)

**Comment by DrSigma4164** [comment]
Hi. Were you able to check on a dedicated server? Because I still haven't been able to check.

However, I developed a script using the KubeJS mod, which when the player enters the world, if he was in a pocket before exiting, teleports to the spawn point, or if this point is in the middle of the pocket, then to certain coordinates (-133, 256, 101). This is for those who encountered this problem before it was resolved.

_`PlayerEvents.loggedIn(event => {
    const { server, player, level } = event
    if (level.dimension == 'dimensionalpocketsii:pocket') { // target dimension == bug dimension
		let respawn = player.getRespawnPosition()
		let respdimension = String(player.getRespawnDimension()).slice(34, -1)
		console.log('KubJS_Fix_DimensionalPocket RespDim: ' + respdimension)
		console.log('KubJS_Fix_DimensionalPocket RespPos: ' + respawn.x + ' ' + respawn.y + ' ' + respawn.z)
		if (respdimension != 'dimensionalpocketsii:pocket') { //If respawn dimension don't equal target dimension than teleport to respawn cord
			console.log('KubJS_Fix_DimensionalPocket TP to respawn pos: ' + respawn.x + ' ' + respawn.y + ' ' + respawn.z + '; in respawn dimension: ' + respdimension + '!')
			player.teleportTo(server.getLevel(respdimension), respawn.x, respawn.y, respawn.z, [], 0, 0)
		} else { // If respawn dimension is same as target dimension than teleport to specified cord
			console.log('KubJS_Fix_DimensionalPocket TP to specified cord!')
			player.teleportTo(server.getLevel('minecraft:overworld'), -133, 256, 101, [], 0, 0)
		}
    }
})`_

The script should be placed in the folder with server scripts, as shown in the photo below.
![image](https://github.com/user-attachments/assets/b5bfaed8-d12c-486f-921d-cf4ccf57beb7)
