### ISSUE TITLE
Make a Server Version

### ISSUE THREAD

**Issue by MGW14** [TheRealZeher/DimensionalPockets-II#28]
We want a Server version.
I think it's not that hard.
Please.

**Comment by TheRealZeher** [comment]
Hi.
I'm really sorry I haven't been able to update the mod much. I will make a server version as soon as I'm settled. I have just moved 120 miles away from my old house to go to university. I admit I haven't had much time to focus on coding. I'll update the mod as soon as I can.

**Comment by TheRealZeher** [comment]
Issue was a legacy line of code that was being run on the client side when entering a pocket. Dimensional Pockets II now works on servers.
