### ISSUE TITLE
Crash when loading on server

### ISSUE THREAD

**Issue by Konstantinell** [TheRealZeher/DimensionalPockets-II#80]
Minecraft Version. [1.18.1]
Mod version. [5.1.0.10]
Cosmos-Library Version. [1.18.1-5.1.2.70]
https://gist.github.com/Konstantinell/c296843714b6b20452dd94029c8c3363

**Comment by TheCosmicNebula** [comment]
Thanks for the report. A fresh release has been uploaded.

Fixed: #1.18.1-5.1.0.30 & #1.17.1-4.1.0.150
