### ISSUE TITLE
Crash on placing pocket block in world

### ISSUE THREAD

**Issue by Ribbons0121R121** [TheRealZeher/DimensionalPockets-II#81]
game crashes when i place down the pocket block, ive updated both the core and forge respectively, and my java runtime is up to date. happening on latest version for 1.18.1.
ive attached the crash report and log
[crash-2022-01-15_17.09.54-server.txt](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/7876069/crash-2022-01-15_17.09.54-server.txt)
[latest.log](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/7876072/latest.log)

**Comment by TheCosmicNebula** [comment]
Issue should be fixed as of 5.1.0.160.
