### ISSUE TITLE
[1.18] Crash on Startup | No Class IBlockEntityChannel$Energy in CosmosLib found

### ISSUE THREAD

**Issue by remplerus** [TheRealZeher/DimensionalPockets-II#82]
When starting forge on a client with Dimensional Pocket version 1.18.1-5.1.3.0 it'll crash as IBlockEntityChannel$Energy is missing in CosmosLib.

Minecraft Version: 1.18.1
Mod version 1.18.1-5.1.3.0
Cosmos-Library Version. 1.18.1-5.1.8.10
Full crash report: https://gist.github.com/remplerus/da7eba2f6c83df77e3b894b1fbee2e1e

**Comment by TheCosmicNebula** [comment]
Hi, from that crash message it appears that you don't have the latest version of CosmosLibrary installed.

**Comment by TheCosmicNebula** [comment]
Failure message: Mod dimensionalpocketsii requires cosmoslibrary 5.1.8 or above
		Currently, cosmoslibrary is 5.1.7.15

**Comment by TheCosmicNebula** [comment]
`Failure message: Mod dimensionalpocketsii requires cosmoslibrary 5.1.8 or above
		Currently, cosmoslibrary is 5.1.7.15`

**Comment by remplerus** [comment]
whoops wrong crashlog, have updated gist

**Comment by TheCosmicNebula** [comment]
From that crash log, it appears you don't have the latest version of Dimensional Pockets II installed.

`dimensionalpocketsii-1.18.1-5.1.2.80-universal.jar|Dimensional Pockets II        |dimensionalpocketsii          |5.1.2.80            |ERROR     |Manifest: NOSIGNATURE`

**Comment by remplerus** [comment]
:| i always try it with earlier version first before i make issue request. i have updated gist again :|

**Comment by remplerus** [comment]
i hate curseforge not deleting old versions :|

**Comment by TheCosmicNebula** [comment]
I have uploaded a fresh version, should be live in the next 10 minutes, just in case.
