### ISSUE TITLE
Crash by cosmoslibrary

### ISSUE THREAD

**Issue by xphost008** [TheRealZeher/DimensionalPockets-II#83]
hey dude
When my mod folder has this lib mod, and I am CreativeMode, when i open my survival bag,this crash is done! after testing,I found this mod is cause in this crash...
if you can fix it, I will pleasure!
[crash-2022-01-06_13.14.39-client.txt](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/8046126/crash-2022-01-06_13.14.39-client.txt)
btw my discord name is lipist.lol,have a good day!

**Comment by xphost008** [comment]
OK,when i in survival mode, I cant open my bag.because when i open it, then it crash......

**Comment by TheCosmicNebula** [comment]
You are not running the latest version of mod. The latest version I'd 1.18.1-5.1.3.10, this issue has been fixed.
