### ISSUE TITLE
Armor Stand Crash

### ISSUE THREAD

**Issue by VanyaBaou** [TheRealZeher/DimensionalPockets-II#84]
**Minecraft Version**: 1.16.5
**Mod Version**: dimensionalpocketsii-1.16.5-1.4.13-universal
**Cosmos-Library Version**: cosmoslibrary-1.16.5-6.8.0-universal
**Full crash report**: https://pastebin.com/z9ia1fXS
**Whether you where running it on a server, or a client**: Client

**Description**:
Armor Stands being created will randomly crash the game.
Replicated by doing "/summon minecraft:armor_stand x y z" a few tens of times
Also occurs with Armor Stands generated in structures.

**Comment by TheCosmicNebula** [comment]
Hi, this is most likely due to changes with Forge and updating to a new version of Forge. I will take a look into this issue.
