### ISSUE TITLE
[1.16.5] Generator Module does not work

### ISSUE THREAD

**Issue by zerofelx** [TheRealZeher/DimensionalPockets-II#85]
The Pocket Generator Module doesn't work directly, it's a bug.

It does not generate FE and when I try to remove an item with Shift + Click the game crashes.

Screenshot: https://imgur.com/a/G5mXCsH

**Comment by TheCosmicNebula** [comment]
This is a known issue, a new MC version came out during the development of this Module. As I have already implemented this in the 1.17.1 version, I will add the functionality to the 1.16.5 version.
