### ISSUE TITLE
1.18.2 will not run with cosmos

### ISSUE THREAD

**Issue by Foxtrot-Flies** [TheRealZeher/DimensionalPockets-II#86]
![image](https://user-images.githubusercontent.com/99414468/168889450-1b853506-585e-4f7c-a1c4-7e54641c4a83.png)
![image](https://user-images.githubusercontent.com/99414468/168889546-db43742c-b0aa-47fc-9cec-bf2e61521621.png)
[latest.log](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/8710826/latest.log)
[crash-2022-05-17_14.52.09-fml.txt](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/8710827/crash-2022-05-17_14.52.09-fml.txt)

Attempting to use the 1.18.1 version on 1.18.2, shouldn't be a big issue and I use other 1.18.1 mods on 1.18.2 at the same time but it is not running and giving me the error code of, java.lang.exceptioninintializererror: null

i understand its 1.18.2 but one minor bug fix update shouldn't be causing this issue so im guessing it was one of the mods, will advise if I find out which mod.

**Comment by TheCosmicNebula** [comment]
1.18.2 is a bigger change than it appears. The 1.18.1 version will *not* work on 1.18.2. A 1.18.2 version will be released in the coming weeks.
