### ISSUE TITLE
[1.12.2] Conflict with BetterPortals

### ISSUE THREAD

**Issue by festro** [TheRealZeher/DimensionalPockets-II#88]
Minecraft 1.12.2
Mod version 5.2.101
Cosmos version 7.2.05
[crash-2022-05-29_19.40.59-server.txt](https://github.com/TheCosmicNebula/DimensionalPocketsII/files/8795057/crash-2022-05-29_19.40.59-server.txt)

Was running Single Player (Don't know if that qualifies a s server or client)
Brought the issue to BetterPortals page https://github.com/Johni0702/BetterPortals/issues/616
"when visiting the pocket Dimension the view gets weird like I'm perpetual falling, all my equipment is gone, but when I get quit to menu and log back in everything is fine, I'm in the pocket dimension, all my gear is there, but when I leave same thing happens again"

Hope this helps.

**Comment by TheCosmicNebula** [comment]
Hi, the 1.12.2 version is End of Life, and as such will not be updated except for Critical Issues. If BetterPortals responds to you please let me know and I may be able to take a look into this.

**Comment by festro** [comment]
The author has marked as waiting for third party https://github.com/Johni0702/BetterPortals/issues/616
