### ISSUE TITLE
[1.18.2] Welcome text is shown to every player, every time at login 

### ISSUE THREAD

**Issue by Saereth** [TheRealZeher/DimensionalPockets-II#89]
Is there a way to turn off this welcome text? The text is not even accurate for this pack as they dont spawn with the tome. (that's turned off in the config in favor of akashic tome integration)
![image](https://user-images.githubusercontent.com/9200909/175396345-68c87eef-db6b-4af0-abf4-85ec3aa10142.png)

**Comment by TheCosmicNebula** [comment]
Hi, I have had many problems with this in the past. There is a config option available to disable it. I will look into why it isn't working as it should.

**Comment by Saereth** [comment]
Thanks! if it helps this is my current config file
https://www.toptal.com/developers/hastebin/ehimebikiv.ini

**Comment by TheCosmicNebula** [comment]
Are you playing on a server or singleplayer?

**Comment by Saereth** [comment]
single player

**Comment by TheCosmicNebula** [comment]
Huh, you shouldn't be getting that message then, as uou have the option disabled. I'll look into it when I'm back from my business trip.

**Comment by Saereth** [comment]
No worries, thanks!

**Comment by TheCosmicNebula** [comment]
I will be looking into this alongside the 1.16.5 version with a view to remove this feature entirely.

**Comment by TheCosmicNebula** [comment]
This issue has been fixed as per Release 6.1.3.40:
https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii/files/4000027
