### ISSUE TITLE
[1.18.2] Server issue

### ISSUE THREAD

**Issue by zzSealzz** [TheRealZeher/DimensionalPockets-II#90]
When i tried to run it on a 1.18.2 server it would run the server but when people tried to join it would give them the error code 

Cannot invoke net.minecraft.resources.Resource Location.toString() because p_130086_ is null fix

i love this mod its my fav but it sucks that i cant use it on my 1.18.2 server so i hope theres a fix

**Comment by TheCosmicNebula** [comment]
Hi, I will investigate this issue as soon as I am able.

**Comment by TheCosmicNebula** [comment]
This issue has now been fixed as of version: 6.1.1.05.
