### ISSUE TITLE
[1.18.2] Ores not generating

### ISSUE THREAD

**Issue by TheRealMatthew4** [TheRealZeher/DimensionalPockets-II#92]
No ores seem to generate
Mod list
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/3896254

https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/create/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/flywheel/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/createaddition/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/files/all?filter-game-version=1738749986%3a73250

https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii

https://www.curseforge.com/minecraft/mc-mods/cosmos-library/files/all?filter-game-version=1738749986%3a73250

**Comment by TheCosmicNebula** [comment]
Ores have been confirmed as generating on the latest release 6.1.3.40:
https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii/files/4000027
