### ISSUE TITLE
1.16.5 How do I remove the advertisement when I start a new world.

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheRealZeher/DimensionalPockets-II#95]
I'd like to add this mod to my modpack (https://www.curseforge.com/minecraft/modpacks/jetpack-cat)

I can't add it while it spits this text on screen, it's unnecessary information as the player can grab any book from any mod from my quest menu. I have instructions I print to the players screen when they start a new world that I want them to pay attention to. The text from dimensional pockets will cause some players to ignore the text I print, thinking it's all just junk text added from mods in the pack.

My modpack isn't called Dimensional Pockets II, and it makes it feel like a junky thrown together kitchen sink modpack if I have individual mods announcing themselves like that.

I don't see an option to turn it off in the server or client config.

![image](https://user-images.githubusercontent.com/100042170/184562175-cdf24835-44b0-434b-b658-bfff7ff43f6f.png)

**Comment by TheCosmicNebula** [comment]
Yes at present there is no way to turn this off, however I will remove this welcome text in the next version, which I plan to release on Friday of this week.

**Comment by Jetpack-Cat** [comment]
awesome thank you! Can you add a config option for the mod to also not give you the book? I logged into a world and it gave me the book, I have the book available for people to grab in the quest menu any time they need it.

**Comment by TheCosmicNebula** [comment]
Fixed as per release 1.5.0 available here:
https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii/files/4000044
