### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by Health1nspector** [TheRealZeher/DimensionalPockets-II#97]
After using this mod. I no longer can open up my 2-year-old Minecraft world..

**Comment by TheCosmicNebula** [comment]
Hi, can you provide more information please? Such as Minecraft version, Mod version, Cosmos Library version, Forge version.

If you can also provide any crash logs etc

**Comment by TheCosmicNebula** [comment]
I am going to close this issue, as I believe it is related to #94
